### ISSUE TITLE
Can't publish because of error on broken link checker

### ISSUE THREAD

**Issue by dmcinnes** [heroku/devcenter-cli#25]
It appears that the devcenter CLI not getting a proper response back from devcenter, or it's not parsing it correctly:

```
➜ devcenter push schema/platform-api-reference.md --trace
The article "schema/platform-api-reference" contains broken link/s:
/Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/push.rb:54:in `[]': no implicit conversion of String into Integer (TypeError)
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/push.rb:54:in `block in display_broken_links'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/push.rb:54:in `each'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/push.rb:54:in `display_broken_links'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/push.rb:27:in `run'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/base.rb:29:in `initialize'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/push.rb:8:in `initialize'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/base.rb:19:in `new'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/commands/base.rb:19:in `run'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/cli.rb:48:in `block (2 levels) in <top (required)>'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/mbusch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```

The response body coming back from devcenter:
```ruby
{""=>[]}
```

/cc @kahlouie @mikelikesbikes

**Comment by raul** [comment]
Sorry about the delay @dmcinnes @kahlouie @mikelikesbikes, this should be fixed now!
