### ISSUE TITLE
Pulling articles stopped working

### ISSUE THREAD

**Issue by saschat** [heroku/devcenter-cli#27]
The last time I used this command was probably last month. Now it does not work any longer. I am logged in with the owner account of the memcachier article.

```
$ devcenter pull -t memcachier
~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/user_interaction.rb:334: warning: constant ::Data is deprecated
Traceback (most recent call last):
	12: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
	11: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	10: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	 9: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	 8: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	 7: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	 6: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devcenter-1.1.8/lib/devcenter/cli.rb:35:in `block (2 levels) in <top (required)>'
	 5: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devcenter-1.1.8/lib/devcenter/commands/base.rb:19:in `run'
	 4: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devcenter-1.1.8/lib/devcenter/commands/base.rb:19:in `new'
	 3: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devcenter-1.1.8/lib/devcenter/commands/pull.rb:8:in `initialize'
	 2: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devcenter-1.1.8/lib/devcenter/commands/base.rb:29:in `initialize'
	 1: from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devcenter-1.1.8/lib/devcenter/commands/pull.rb:20:in `run'
~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devcenter-1.1.8/lib/devcenter/commands/base.rb:42:in `article_not_found!': undefined method `select!' for nil:NilClass (NoMethodError)
```

**Comment by saschat** [comment]
Just to be clear, this error only happens when pulling. Pushing articles works as intended.

**Comment by hannesfostie** [comment]
@saschat I've pushed version `1.1.9` which should resolve the error you've been encountering. Let me know if you find any other issues!

**Comment by saschat** [comment]
Works like a charm now, thanks a lot!
